power <- read.table("household_power_consumption.txt",header=TRUE,sep=";")
power$Date <- as.Date(power$Date,"%d/%m/%Y")
power2 <- as.data.table(power)  
dts <- power2[Date=="2007-02-01"|Date=="2007-02-02",]
gpts <-ts(data = dts$Global_active_power)
volt <- ts(data = dts$Voltage)
sm1 <- ts(data = dts$Sub_metering_1)
sm2 <- ts(data = dts$Sub_metering_2)
sm3 <- ts(data = dts$Sub_metering_3)
grp <- ts(data = dts$Global_reactive_power)
png(file="plot4.png",width=480,height=480)
par(mfrow=c(2,2))
plot(gpts,ylab="Global Active Power (kilowatts)")
plot(volt,ylab="Voltage",xlab="datetime")
plot(sm1,ylab="Energy sub metering")
  lines(sm2,col="red")
  lines(sm3,col="blue")
  legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1,col=c("black","red","blue"))
plot(grp,ylab="Global_reactive_power",xlab="datetime")
dev.off()
